server:
  port: 8082

spring:
  application:
    name: wallet-service
  datasource:
    url: jdbc:postgresql://localhost/wallet_serv_db
    username: postgres
    password: YOUR_PASSWORD
  jpa:
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: update
  devtools:
    restart:
      enabled: true

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/